### ISSUE TITLE
Requesting BreakEven breaks the script

### ISSUE THREAD

**Issue by berland** [equinor/stea#24]
If one requests BreakEven, as suggested by the web api docs, the STEA web client will add BreakEven results, but the Python code handling the response fails, because the breakeven results ends up in a different data structure

**Comment by berland** [comment]
Valid configuration for the STEA API:
```
results:
   - NPV
   - IRR
   - CEI
   - BreakEven
   - Cashflow
   - AnalysisForCompany
```

Results in: 
```
Traceback (most recent call last):
  File "/project/fd/Nokken/resmod/nokken/2017/users/khgu/r001_base_frac/ert/bin/scripts/stea_fmu.py", line 73, in <module>
    main(sys.argv)
  File "/xxxx/r001_base_frac/ert/bin/scripts/stea_fmu.py", line 45, in main
    pretax_fh.write(json.dumps(res.results(stea.SteaKeys.PRETAX)))
  File "/xxxx/stea/stea_result.py", line 16, in results
    res[res_key] = value_dict[SteaKeys.VALUES][res_key]
KeyError: 'BreakEven'
```

**Comment by berland** [comment]
```
$ (main) git diff
diff --git a/tests/test_integration.py b/tests/test_integration.py
index c99c50f..efabbaf 100644
--- a/tests/test_integration.py
+++ b/tests/test_integration.py
@@ -19,6 +19,7 @@ ecl-profiles:
 ecl-case: {}
 results:
   - NPV
+  - BreakEven
 """
 
 BASE_ERT_CONFIG = """

```
This will yield a test failure in  `tests/test_integration.py`

**Comment by oyvindeide** [comment]
This has very low priority as no users have reported this, so marking it as wontfix.

**Comment by berland** [comment]
> This will yield a test failure in `tests/test_integration.py`

This fails due to the mocked response that only returns NPV.

**Comment by berland** [comment]
BreakEven is not returned from Stea in all cases. Probably a user error.
